First
DmytroBylkov/oop pull request #5
Opened 2022-12-04 17:51 UTC by DmytroBylkov

Додав магічні методи __eq__, __float__, __repr__ до класу Product
До класу ShoppingCart додав магычны методи __init__, __len__, __float__,__str__, __add__
Невийшло реалізувати методи, що в кошику б при додавання того ж товару змінював би кількість наявного, та видалення продукту з кошику. Можливо краще використовувати не список, для продуктів у кошику, а щось інше?

2022-12-04 21:09 UTC, shorodilov requested changes
Потребує змін

2022-12-04 21:09 UTC, shorodilov commented on main.py
> +        return self.name == other.name and self.price == other.price
Це спрацює лише для порівняння об'єктів класу `Product`.
Сюди треба додати перевірку типів. Можна просто повертати `False`, якщо тип не збігається.

2022-12-04 21:09 UTC, shorodilov commented on main.py
> +        products_in_cart = []
Нащо ці рухи туди-сюди?
```suggestion
        self.products = []
```

2022-12-04 21:09 UTC, shorodilov commented on main.py
> +        return self.products_in_cart
Метод `__str__` (як і `__repr__`) повинен повертати рядок.

2022-12-04 21:09 UTC, shorodilov commented on main.py
>          return sum
Не забувай про скруглення

2022-12-04 21:09 UTC, shorodilov commented on main.py
> +        self.products_in_cart = self.products_in_cart + other.products_in_cart
Ліпше створюй новий кошик, не треба змінювати поточний.
І ще треба додати поведінку для випадку `cart_obj + product_obj`

2022-12-05 12:54 UTC, DmytroBylkov commented
Добрий день! Вніс правки за рекомендаціями. Лише округлення не вводив, так як воно відбувається в методі qet_total класу  Product

2022-12-05 12:58 UTC, shorodilov requested changes
Потребує виправлення

2022-12-05 12:58 UTC, shorodilov commented on main.py
>          return sum
Не забувай про округлення.

2022-12-05 12:58 UTC, shorodilov commented on main.py
> +        return True
У цьому разі будь який кошик еквівалент будь якому. Треба додати логіку порівняння.

2022-12-05 12:58 UTC, shorodilov commented on main.py
> +        return "".join(f"{product.__repr__()}: {quantity}, " for product, quantity in self.products)
```python
", ".join(...)
```

2022-12-05 12:58 UTC, shorodilov commented on main.py
> +            return print("You can add only cart to cart")
Що повертає `print`?

2022-12-05 12:58 UTC, shorodilov commented on main.py
> +        if self.__eq__(other):
Що робить оцей рядок?

2022-12-05 12:59 UTC, shorodilov commented
> Добрий день! Вніс правки за рекомендаціями. Лише округлення не вводив, так як воно відбувається в методі qet_total класу  Product. Та із створенням нового кошику не догнав ще, бо як тоді прописати щоб клас тепер не кошик products використовував у подальшому, а інший?

Не зрозумів питання

2022-12-05 13:14 UTC, shorodilov requested changes
Потребує виправлень

2022-12-05 13:14 UTC, shorodilov commented on main.py
>      def __add__(self, other):
```python
cart_obj + 1
```
???

2022-12-05 13:47 UTC, DmytroBylkov commented on main.py
> +        if self.__eq__(other):
перевіряє чи додається обєкт класу кошик, та якщо істина проходить додавання, інакше повертає print

2022-12-05 14:31 UTC, DmytroBylkov commented on main.py
> +            return print("You can add only cart to cart")
Прінт повертає в консоль коли не відбулося додавання обєкту, так як обєкт не пройшов порівняння

2022-12-05 14:31 UTC, DmytroBylkov commented on main.py
>      def __add__(self, other):
додав вже опис що має бути обєкт класу ShoppingCart

2022-12-05 14:31 UTC, DmytroBylkov commented on main.py
> +        return "".join(f"{product.__repr__()}: {quantity}, " for product, quantity in self.products)
виправив

2022-12-05 15:04 UTC, DmytroBylkov commented on main.py
>          return sum
Округлення в методі класу Product
def get_total(self, quantity: float):
        """calculating total price for product"""

        return round(quantity * self.price, 2)

2022-12-05 15:07 UTC, shorodilov commented on main.py
> +        if self.__eq__(other):
Не вірна відповідь. Він перевіряє `self == other`.
Навіщо це тут?

2022-12-05 15:08 UTC, shorodilov commented on main.py
> +            return print("You can add only cart to cart")
`print` нічого не повертає.
Отже - що повертає твій метод?

2022-12-05 15:08 UTC, shorodilov commented on main.py
>          return sum
`0.1 + 0.2`???

2022-12-05 15:11 UTC, shorodilov requested changes
Потребує виправлень

2022-12-05 15:11 UTC, shorodilov commented on main.py
> +        products = []
Навіщо?

2022-12-05 15:24 UTC, DmytroBylkov commented on main.py
> +        products = []
Та в умові завдання було додати конструктори до класів... До ShoppingCart можна не робити?

2022-12-05 15:24 UTC, DmytroBylkov commented on main.py
> +        if self.__eq__(other):
Я подумав, що якщо є метод перевірки, то при додаванні обєктів якраз і треба перевіряти чи додаються обєкти однакового класу

2022-12-05 15:25 UTC, shorodilov requested changes
Потребує змін

2022-12-05 15:25 UTC, shorodilov commented on main.py
> +        if self.__eq__(other):
Це все ще не виправлено.
Я бажаю поведінку `new_cart = cart_obj1 + cart_obj2` та `new_cart = cart_obj + product_obj`

2022-12-05 15:29 UTC, shorodilov commented on main.py
> +        products = []
Навіщо саме так.
У чому різниця з
```python
self.products = []
```

2022-12-05 15:29 UTC, shorodilov commented on main.py
> +        products = []
???

2022-12-06 13:13 UTC, shorodilov requested changes
Потребує допрацювання.
Загальне зауваження, щодо організації коду.
Методи ліпше впорядкувавати у межах класу: спочатку дандери, потім проперті, методи класу та статичні, потім методи інстансів, бо інакше важко шукати. От я не одразу знайшов `ShoppingCart.__str__` і навіть написав коментар, що за його відсутності перерівка кошиків на `==` буде йти інакше.

2022-12-06 13:13 UTC, shorodilov commented on main.py
> +        if self.__eq__(other):
> Я подумав, що якщо є метод перевірки, то при додаванні обєктів якраз і треба перевіряти чи додаються обєкти однакового класу

То все вірно ти подумав.
Але треба саме таку поведінку прописати, а не використати якийсь рандомний метод.

2022-12-06 13:13 UTC, shorodilov commented on main.py
> +        return f'{self.name}'
Це робити не обов'язково, у тебе і без того `self.name: str`.
Не помилка, але вводить в оману - треба буде виправити якось.

2022-12-06 13:13 UTC, shorodilov commented on main.py
> +        if other.__repr__() == 'Product':
Користуйся `isinstance` для перевірки класу об'єкту.

2022-12-06 13:13 UTC, shorodilov commented on main.py
> +        return self.__str__() == other.__str__()
```suggestion
        return set(self.products) == set(other.products)
```

2022-12-06 14:56 UTC, shorodilov submitted a review, later dismissed
LGTM

2022-12-06 15:20 UTC, shorodilov requested changes

2022-12-06 15:20 UTC, shorodilov commented on main.py
> +    def __add__(self, other, quantity=1):
```suggestion
    def __add__(self, other):
```

2022-12-06 15:20 UTC, shorodilov commented on main.py
> +    def __add__(self, other, quantity=1):
Додай окремий метод для того, щоб складати товар до кошика.
Звідси просто виклакай його з quantity=1 якщо `cart_obj + product_obj`

2022-12-07 09:23 UTC, shorodilov approved these changes
Начебто тепер все ок

2022-12-07 11:00 UTC, shorodilov approved these changes
lgtm

2022-12-07 11:02 UTC, merged